-------------------------------------------------------------------------------
Test set: testRunners.MyTestRunner
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 103.293 s <<< FAILURE! - in testRunners.MyTestRunner
null on testRunners.MyTestRunner(testRunners.MyTestRunner)  Time elapsed: 103.135 s  <<< FAILURE!
java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
Caused by: java.net.ConnectException: Connection refused: connect

